from django.urls import path
from .views import (
    CategoryListView,
    CategoryDetailView,
    ProductListView,
    ProductDetailView,
    SellerListView,
    SellerProductListCreateView,
    SellerStatsView,
    SellerOrdersView,
    SellerProductDetailView,
    SellerProfileView,
    SellerProductImageView,
    SellerOrderStatusView,
    FavoriteListView,
    FavoriteCreateView,
    FavoriteDeleteView,
)

urlpatterns = [
    path("categories/", CategoryListView.as_view(), name="category-list"),
    path("categories/<int:pk>/", CategoryDetailView.as_view(), name="category-detail"),
    path("products/", ProductListView.as_view(), name="product-list"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="product-detail"),
    path("sellers/", SellerListView.as_view(), name="seller-list"),
    path("seller/products/", SellerProductListCreateView.as_view(), name="seller-products"),
    path("seller/products/<int:pk>/", SellerProductDetailView.as_view(), name="seller-product-detail"),
    path("seller/products/<int:product_id>/images/", SellerProductImageView.as_view(), name="seller-product-images"),
    path("seller/profile/", SellerProfileView.as_view(), name="seller-profile"),
    path("seller/stats/", SellerStatsView.as_view(), name="seller-stats"),
    path("seller/orders/", SellerOrdersView.as_view(), name="seller-orders"),
    path("seller/orders/<int:order_id>/status/", SellerOrderStatusView.as_view(), name="seller-order-status"),
    path("favorites/", FavoriteListView.as_view(), name="favorite-list"),
    path("favorites/add/", FavoriteCreateView.as_view(), name="favorite-create"),
    path("favorites/<int:pk>/", FavoriteDeleteView.as_view(), name="favorite-delete"),
]
